config/routes.rb
Rails.application.routes.draw do
  resources :organizations do
    resources :repos do
      resources :commits do
        get :master, on: :collection
      end
      resources :branches do
        get :commits, on: :member
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_client
  before_action :set_user

  def set_client
    @client = Octokit::Client.new(
      #access_token: '173c2794fd1c4f74bcdf67e08e9de0917129a2c9'
      access_token: ''
    )
  end

  def set_user
    @user = @client.user account_user
  end

  def account_user
    @client.root.rels[:current_user].get.data.login
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_repo

  def index
    @branches = @repo.rels[:branches].get.data
  end

  def show
    @repo_rels = @repo.rels
    @commits = @repo_rels[:commits].get.data
  end

  private
  def set_repo
    @repo = @client.repo "#{account_user}/#{params[:repo_id]}"
  end
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  before_action :set_repo

  def index
    template = @repo.rels[:commits].get
    @commits = get_commits(template)
  end

  def master
    template = @repo.rels[:commits].get
    all_commits = get_commits(template)
    first_commit = get_first_commit(all_commits.reverse)

    @commits = get_master_commits_by_committer(all_commits, "GitHub", params[:from_at], params[:to_at], params[:author])

    @authors = @commits.map { |x| OpenStruct.new({name: "#{x.commit.author.name} <#{x.commit.author.email}>", email: x.commit.author.email }) }.uniq



  end

  private

  def get_master_commits_by_committer(commits, committer, from_at, to_at, author)
    filter_commits = commits.select { |c| c.commit.committer.email == "noreply@github.com" }
    filter_commits = filter_commits.select { |c| c.commit.committer.date >= from_at} unless from_at.nil?
    filter_commits = filter_commits.select { |c| c.commit.committer.date <= to_at} unless to_at.nil?
    filter_commits = filter_commits.select { |c| c.commit.author.email == author} unless author.nil?
    filter_commits
  end

  def get_master_commits(commits, master_commit)
    next_commit = commits.detect{|w| w.parents.count == 2 && w.parents.select { |p| p[:sha] == master_commit.sha }.count > 0 }
    next_commit = commits.detect{|w| w.parents.count == 1 && w.parents.select { |p| p[:sha] == master_commit.sha }.count > 0 } if next_commit.nil?
    unless next_commit.nil?
      master_commits = get_master_commits(commits, next_commit)
    end
    return (master_commits.to_a + [next_commit]).compact
  end

  def get_commits(template)
    next_rel = template.rels[:next]
    unless next_rel.nil?
      commits = get_commits(next_rel.get)
    end
    return template.data + commits.to_a
  end

  def get_first_commit(commits)
    commits.detect{|w| w.parents.empty? }
  end

  def set_repo
    @repo = @client.repo "#{params[:organization_id]}/#{params[:repo_id]}"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index;
    @account_user = account_user
    @organizations = @client.root.rels[:user_organizations].get.data
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def show
    @organization = params[:id]
    uri = { }
    root = @client.root

    repo_rel = if @organization.nil? || @organization == account_user
      uri = { user: @organization}
      root.rels[:current_user_repositories]
    else
      uri = { org: @organization}
      root.rels[:organization_repositories]
    end
    @private_repos = get_repos(repo_rel, uri, { type: 'private' })
    @public_repos = get_repos(repo_rel, uri, { type: 'public' })
  end

  private

  def get_repos(repo_rel, uri, query)
    template = repo_rel.get(uri: uri, query: query)
    next_rel = template.rels[:next]
    unless next_rel.nil?
      repos = get_repos(next_rel, uri, query)
    end
    return template.data + repos.to_a
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  def index
    organization = params[:organization]
    repo_rel = unless organization.nil?
      root = @client.root
      uri = { org: organization}
      query = { type: 'private' }
      root.rels[:organization_repositories]
    else
      uri = { }
      query = { }
      @user.rels[:repos]
    end
    @repos = get_repos(repo_rel, uri, query)
  end

  def show
    organization = params[:organization_id]
    @repo = @client.repo "#{organization}/#{params[:id]}"
    @rels = @repo.rels
    @branches = @repo.rels[:branches].get.data
  end

  private

  def get_repos(repo_rel, uri, query)
    template = repo_rel.get(uri: uri, query: query)
    next_rel = template.rels[:next]
    unless next_rel.nil?
      repos = get_repos(next_rel, uri, query)
    end
    return template.data + repos.to_a
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/commits_helper.rb
module CommitsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/branches/_list.html.erb
<% @branches.each do |branch| %>
  <div>
    <div>
      <span>
        <% #= branch.inspect %>
        <%= link_to branch.commit.sha, repo_branch_path(params[:repo_id], branch.commit.sha) %>
      </span>
       -
      <span><%= branch.name %></span>
    </div>
  </div>
<% end %>

app/views/branches/index.html.erb
<div><b>Branches</b></div>

<%= render "list" %>

app/views/branches/show.html.erb
<% #= @repo.inspect %>

<%= @repo_rels.inspect %>
<% #= @commidt_rels.inspect %>
<% #@rels.each do |rel| %>
  <div>
    <%#= rel.inspect %>
  </div>
<% #end %>

<% #= render "branches" %>

<div>
  <% #= link_to "Pull requests", pulls_repo_branch_path(params[:repo_id], params[:id]) %>
</div>

app/views/commits/_list.html.erb
<%= form_with url: master_organization_repo_commits_path(params[:organization_id],params[:repo_id]), method: :get, local: true do |f| %>
  <%= f.datetime_field :from_at, value: params[:from_at], required: true %>
  <%= f.datetime_field :to_at, value: params[:to_at], required: true %>
  <%= f.collection_select(:author, @authors, :email, :name) %>
  
  <%= f.submit "Filtrar", class: '' %>
<% end %>

<div>
  <b>
    Total:
  </b>
  <%= @commits.count %>
</div>

<% @commits.each do |commit| %>
  <% #= commit.inspect %>
  <div>
    <div>sha <%= commit.sha %></div>
    <div>
      commiter
      <%= commit.commit.committer.name %>
    </div>
    <div>
      author
      <%= commit.commit.author.name %>
    </div>
    <div>
      date
      <%= commit.commit.committer.date %>
    </div>
    <div>tree <%= commit.commit.tree.sha %></div>
    <div>message <%= commit.commit.message %></div>
    <div>
      <div><b>Parents</b></div>
      <% commit.parents.each do |parent| %>
        <div><%= parent.sha %></div>
      <% end %>
    </div>
    <br />
  </div>
  <br />
<% end %>

app/views/commits/index.html.erb
<div><b>Commits</b></div>

<%= render "list" %>

app/views/commits/master.html.erb
<div><b>Commits</b></div>

<%= render "list" %>

app/views/commits/master_from_initial.html.erb
<div><b>Commits</b></div>

<%= render "list" %>

app/views/home/index.html.erb
<div>
  <div>
    <b>
      Personal
    </b>
  </div>
  <div>
    <%= link_to @account_user, organization_path(id: @account_user) %>
  </div>
</div>
<br />
<div>
  <div>
    <b>
      Organizaciones
    </b>
  </div>
  <div>
    <% @organizations.each do |organization| %>
      <div>
        <%= link_to organization.login, organization_path(id: organization.login) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubData</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/organizations/_info.html.erb
<div>
  <h3>
    <%= @organization %>
  </h3>
</div>

app/views/organizations/show.html.erb
<%= render "info" %>
<div>
  <h4>
  Repositorios
  </h4>
</div>

<div>
  <b>
  Privados
  </h4>
</b>
<% @private_repos.each do |repo| %>
  <% #= repo.inspect %>
  <div>
    <%= link_to repo.name, organization_repo_path(repo.owner.login, repo.name) %>
  </div>
<% end %>
<br />
<div>
  <b>
  Publicos
  </h4>
</b>
<% @public_repos.each do |repo| %>
  <div>
    <%= link_to repo.name, organization_repo_path(@organization, repo.name) %>
  </div>
<% end %>
<div>
  <% #= link_to "Commits", repo_commits_path(params[:id]) %>
</div>

<div>
  <% #= link_to "Master commits", master_repo_commits_path(params[:id]) %>
</div>

<div>
  <% #= link_to "Branches", repo_branches_path(params[:id]) %>
</div>

app/views/repos/_branches.html.erb
<div><b>Branches</b></div>
<% @branches.each do |branch| %>
  <div>
    <div>
      <span><%= link_to branch.commit.sha, repo_branch_path(params[:id], branch.commit.sha) %></span>
       -
      <span><%= branch.name %></span>
    </div>
  </div>
<% end %>

app/views/repos/_commits.html.erb
<div><b>Commits</b></div>
<% @commits.each do |commit| %>
  <% #= commit.inspect %>
  <div>
    <div>sha <%= commit.sha %></div>
    <div>
      <div><b>Parents</b></div>
      <% commit.parents.each do |parent| %>
        <div><%= parent.sha %></div>
      <% end %>
    </div>
    <br />
  </div>
  <br />
<% end %>

app/views/repos/_info.html.erb
<div>
  <b>
    Repositorio
    <%= @repo.name %>
  </b>
  <div>
    id
    <%= @repo.id %>
  </div>
</div>

app/views/repos/_merges.html.erb
<div><b>Merges</b></div>
<% @merges.each do |merge| %>
  <div>
    <span><% #= merge.commit.sha %></span>
       -
    <span><%= merge.inspect %></span>
  </div>
<% end %>

app/views/repos/index.html.erb
<% #= @repos.inspect %>
<% @repos.each do |repo| %>
  <div>
    <%= link_to repo.name, repo_path(repo.name) %>
  </div>
<% end %>

app/views/repos/show.html.erb
<%= render "info" %>
<div>
  <%= link_to "Commits", organization_repo_commits_path(params[:organization_id], params[:id]) %>
</div>

<div>
  <%= link_to "Master commits", master_organization_repo_commits_path(params[:organization_id], params[:id]) %>
</div>

<div>
  <%= link_to "Branches", organization_repo_branches_path(params[:organization_id], params[:id]) %>
</div>